### ISSUE TITLE
Mini-tool sliders no longer functioning

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#50]
The sliders on the Financial Freedom Calculator are not functioning.

Example: https://maybe.co/tools/financial-freedom-calculator

https://github.com/maybe-finance/marketing/assets/35243/c5ff9755-8e1a-4a0e-84f7-6063a2767bc1

Potentially related console error: `Error: The input type "number" is not supported by autoNumeric`

![CleanShot 2024-06-07 at 11 15 13@2x](https://github.com/maybe-finance/marketing/assets/35243/c5b4ecdf-37dd-48ce-8f73-54bd469bd669)

Potentially relevent code...
* https://github.com/maybe-finance/marketing/blob/main/app/javascript/controllers/financial_freedom_calculator_controller.js
* https://github.com/maybe-finance/marketing/blob/main/app/views/tools/_financial_freedom_calculator.html.erb

**Comment by JoshAntBrown** [comment]
This is because the autonumeric controller is failing to initialize properly. It seems the last few PR's keep changing unit_field helper to render a type number input. Autonumeric won't work on number inputs. Looks like it broke in #48.

https://github.com/maybe-finance/marketing/blob/98acebe5a4724b0e8a52b5c3e0724427be74656a/app/helpers/application_form_builder.rb#L39

This line needs changing back to `text_field`. It's probably due a bit of a refactor now since several of the calculators are using this field. It may be worth making this a dedicated `autonumeric_field` that applies the `autonumeric` Stimulus controller and pass down any appropriate options. That way it might be clearer that this must be a text field.

Autonumeric forms will include the commas too so any calculators that have been built that aren't expecting that would need to be updated if they're to use the same input.

Unfortunately I'm away travelling at the moment so it'll be hard for me to do any code change to fix this properly across all the calculators.

**Comment by LEstradioto** [comment]
Ive changed this to `text_field` in my recent PR #51

**Comment by Shpigford** [comment]
Fixed #51
